source 'https://rubygems.org'

gem 'puma'
gem 'sinatra', git: 'https://github.com/sinatra/sinatra'
gem 'mysql2'
gem 'mysql2-cs-bind'
gem 'bcrypt'
# gem 'newrelic_rpm'
gem 'rack-lineprof'
gem 'pry'
gem 'typhoeus'
gem 'redis'
gem 'hiredis'

group :development do
  gem 'sinatra-contrib'
end
